#!/bin/bash
R=$(osascript -l JavaScript -e 'ObjC.import("AppKit"); var a=$.NSRunningApplication.runningApplicationsWithBundleIdentifier("com.kakao.KakaoTalkMac.second"); if (a.count === 0) { "open" } else { var app=a.objectAtIndex(0); if (app.active) { app.hide; "hidden" } else { "open" } }')
[ "$R" = "open" ] && open "/Users/user/Applications/KakaoTalk 2.app"
exit 0
